services:
  app:
    build: .
    container_name: coffee_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    command: sh -c "composer install &&php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: coffee_db
    environment:
      POSTGRES_DB: coffee_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
